apiVersion: v1
kind: Service 
metadata:
  name: fleetman-webapp

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: webapp
  
  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
---
apiVersion: v1
kind: Service 
metadata:
  name: fleetman-queue

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: fleetman-queue
    release: "0" 
  
  ports:
    - name: http
      port: 8161
      nodePort: 30010

  type: NodePort