apiVersion: v1
kind: Service 
metadata:
  name: fleetman-webapp

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: webapp
  
  ports:
    - name: http
      port: 80

  type: LoadBalancer
---
apiVersion: v1
kind: Service 
metadata:
  name: fleetman-queue

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: queue 
  
  ports:
    - name: http
      port: 8161

    - name: endpoint 
      port: 61616
      
  type: ClusterIP
---
apiVersion: v1
kind: Service 
metadata:
  name: fleetman-position-tracker

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: position-tracker 
  
  ports:
    - name: http
      port: 8080
      
  type: ClusterIP
---
apiVersion: v1
kind: Service 
metadata:
  name: fleetman-api-gateway

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: api-gateway
  
  ports:
    - name: http
      port: 8080
            
  type: ClusterIP