apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata: 
      labels: 
        app: mongodb

    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

        # env: 
        # - name: SPRING_PROFILES_ACTIVE
        #   value: production-microservice
---
apiVersion: v1
kind: Service 
metadata:
  name: fleetman-mongodb

spec:
  #this defines which pods are going to be represented by this services 
  # the service becomes network endoiubt for either other services 
  # or maybe external users to connect 
  
  selector:
    app: mongodb
  
  ports:
    - name: mongoport
      port: 27017
            
  type: ClusterIP